'use client';

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { FileCog, Download } from "lucide-react";
import React, { useState, useRef } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import * as XLSX from "xlsx";

export default function ReportFormatGeneratorPage() {
    const reportPreviewRef = useRef<HTMLDivElement>(null);
    const [downloadFormat, setDownloadFormat] = useState("pdf");

    // State to manage the live preview
    const [fields, setFields] = useState({
        incidentSummary: true,
        complianceStatus: true,
        financials: false,
        mechanizationProgress: true,
        recognitionAwards: false,
    });

    const handleFieldChange = (field: keyof typeof fields, checked: boolean) => {
        setFields(prev => ({ ...prev, [field]: checked }));
    };

    const handleDownload = async () => {
        if (reportPreviewRef.current) {
            if (downloadFormat === 'pdf') {
                const canvas = await html2canvas(reportPreviewRef.current);
                const imgData = canvas.toDataURL('image/png');
                const pdf = new jsPDF();
                const imgProps= pdf.getImageProperties(imgData);
                const pdfWidth = pdf.internal.pageSize.getWidth();
                const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
                pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
                pdf.save("report.pdf");
            } else if (downloadFormat === 'doc') {
                const htmlContent = reportPreviewRef.current.innerHTML;
                const response = await fetch('/api/generate-doc', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ htmlContent }),
                });

                if (response.ok) {
                    const blob = await response.blob();
                    const link = document.createElement('a');
                    link.href = URL.createObjectURL(blob);
                    link.download = 'report.docx';
                    link.click();
                } else {
                    console.error('Failed to generate DOCX');
                }
            } else if (downloadFormat === 'spreadsheet') {
                const data = Object.entries(fields)
                    .filter(([, value]) => value)
                    .map(([key]) => {
                        switch (key) {
                            case 'incidentSummary': return { Section: 'Incident Summary' };
                            case 'complianceStatus': return { Section: 'Compliance Status' };
                            case 'financials': return { Section: 'Financials / Budget Utilization' };
                            case 'mechanizationProgress': return { Section: 'Mechanization Progress' };
                            case 'recognitionAwards': return { Section: 'Recognition & Awards Summary' };
                            default: return { Section: '' };
                        }
                    });

                const ws = XLSX.utils.json_to_sheet(data);
                const wb = XLSX.utils.book_new();
                XLSX.utils.book_append_sheet(wb, ws, "Report");
                XLSX.writeFile(wb, "report.xlsx");
            }
        }
    };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-gray-900">Report Generator</h2>
        <p className="text-gray-600">Define the structure, generate and download official reports across the ecosystem.</p>
      </div>

      <Card className="bg-white shadow-sm border border-gray-200">
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <FileCog className="h-5 w-5 text-blue-600" />
            <span>Report Template Configuration</span>
          </CardTitle>
          <CardDescription>
            Changes made here will apply to all future reports generated by State and District administrations.
          </CardDescription>
        </CardHeader>
        <CardContent className="grid lg:grid-cols-3 gap-6 p-6">
          {/* Step 1: Select Template */}
          <div className="space-y-4 p-4 bg-gray-50 rounded-lg border">
            <div className="flex items-center space-x-3">
              <div className="flex items-center justify-center h-8 w-8 rounded-full bg-blue-500 text-white font-bold">1</div>
              <h3 className="font-semibold text-lg">Select Report Template</h3>
            </div>
            <p className="text-sm text-gray-600">Choose the report template you want to configure.</p>
            <Select>
              <SelectTrigger><SelectValue placeholder="e.g., State Monthly Summary..." /></SelectTrigger>
              <SelectContent>
                <SelectItem value="state-monthly">State Monthly Summary</SelectItem>
                <SelectItem value="district-monthly">District Monthly Compliance</SelectItem>
                <SelectItem value="contractor-perf">Contractor Performance Audit</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Step 2: Configure Fields */}
          <div className="space-y-4 p-4 bg-gray-50 rounded-lg border">
            <div className="flex items-center space-x-3">
              <div className="flex items-center justify-center h-8 w-8 rounded-full bg-blue-500 text-white font-bold">2</div>
              <h3 className="font-semibold text-lg">Configure Data Fields</h3>
            </div>
            <p className="text-sm text-gray-600">Check the boxes to mark a data section as mandatory for this report.</p>
            <div className="mt-2 space-y-3 text-sm p-3 bg-white rounded-md border">
              <div className="flex items-center"><Checkbox id="field1" checked={fields.incidentSummary} onCheckedChange={(c) => handleFieldChange('incidentSummary', !!c)}/><Label htmlFor="field1" className="ml-2 font-normal">Incident Summary</Label></div>
              <div className="flex items-center"><Checkbox id="field2" checked={fields.complianceStatus} onCheckedChange={(c) => handleFieldChange('complianceStatus', !!c)}/><Label htmlFor="field2" className="ml-2 font-normal">Compliance Status</Label></div>
              <div className="flex items-center"><Checkbox id="field3" checked={fields.financials} onCheckedChange={(c) => handleFieldChange('financials', !!c)}/><Label htmlFor="field3" className="ml-2 font-normal">Financials / Budget Utilization</Label></div>
              <div className="flex items-center"><Checkbox id="field4" checked={fields.mechanizationProgress} onCheckedChange={(c) => handleFieldChange('mechanizationProgress', !!c)}/><Label htmlFor="field4" className="ml-2 font-normal">Mechanization Progress</Label></div>
              <div className="flex items-center"><Checkbox id="field5" checked={fields.recognitionAwards} onCheckedChange={(c) => handleFieldChange('recognitionAwards', !!c)}/><Label htmlFor="field5" className="ml-2 font-normal">Recognition & Awards Summary</Label></div>
            </div>
          </div>

          {/* Step 3: Preview and Save */}
          <div className="space-y-4 p-4 bg-gray-50 rounded-lg border">
            <div className="flex items-center space-x-3">
              <div className="flex items-center justify-center h-8 w-8 rounded-full bg-blue-500 text-white font-bold">3</div>
              <h3 className="font-semibold text-lg">Preview & Generate Report</h3>
            </div>
            <p className="text-sm text-gray-600">A live preview of the report structure based on your selections.</p>
            <div ref={reportPreviewRef} className="p-4 border-2 border-dashed rounded-lg bg-white">
              <h4 className="font-bold text-center">State Monthly Summary</h4>
              <p className="text-xs text-center text-gray-500 mb-4">Template Preview</p>
              <ul className="list-disc pl-5 text-sm space-y-1 text-gray-700">
                {fields.incidentSummary && <li>Section: Incident Summary</li>}
                {fields.complianceStatus && <li>Section: Compliance Status</li>}
                {fields.financials && <li>Section: Financials / Budget Utilization</li>}
                {fields.mechanizationProgress && <li>Section: Mechanization Progress</li>}
                {fields.recognitionAwards && <li>Section: Recognition & Awards Summary</li>}
                {!Object.values(fields).some(v => v) && <p className="text-xs text-gray-500">No sections selected.</p>}
              </ul>
            </div>
            <div className="space-y-2 mt-4">
                <Label htmlFor="format">Download Format</Label>
                <Select value={downloadFormat} onValueChange={setDownloadFormat}>
                    <SelectTrigger id="format">
                        <SelectValue placeholder="Select format" />
                    </SelectTrigger>
                    <SelectContent>
                        <SelectItem value="pdf">PDF</SelectItem>
                        <SelectItem value="doc">DOC</SelectItem>
                        <SelectItem value="spreadsheet">Spreadsheet</SelectItem>
                    </SelectContent>
                </Select>
            </div>
             <Button onClick={handleDownload} className="w-full bg-blue-600 hover:bg-blue-700 text-white mt-4">
                <Download className="h-4 w-4 mr-2"/>
                Generate & Download Report
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}